# Generated by Django 3.2.3 on 2021-08-11 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c688f3fa-1b78-4d4d-9e48-2e81af041cde'), editable=False, primary_key=True, serialize=False),
        ),
    ]
