# Generated by Django 3.2.3 on 2021-08-11 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e0eb0b41-8ab8-4a4d-954e-7215931c9ce3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
